development:
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  database: buy-my-beer-development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  database: buy-my-beer-test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  database: buy-my-beer-production
  pool: 5

cucumber:
  <<: *test